// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNbKHg9KrTJUajMjcTHTqz-nYJXRTufUg',
    appId: '1:551484186975:android:05a84133ac7f052e5016ea',
    messagingSenderId: '551484186975',
    projectId: 'travelapp-8e93c',
    authDomain: 'travelapp-8e93c.firebaseapp.com',
    storageBucket: 'travelapp-8e93c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNbKHg9KrTJUajMjcTHTqz-nYJXRTufUg',
    appId: '1:551484186975:android:05a84133ac7f052e5016ea',
    messagingSenderId: '551484186975',
    projectId: 'travelapp-8e93c',
    storageBucket: 'travelapp-8e93c.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDNbKHg9KrTJUajMjcTHTqz-nYJXRTufUg',
  //   appId: '1:551484186975:android:05a84133ac7f052e5016ea',
  //   messagingSenderId: '551484186975',
  //   projectId: 'travelapp-8e93c',
  //   storageBucket: 'fir-auth-demo-ec48c.appspot.com',
  //   iosClientId: '599030350718-rt5diuiggpna5fmco6k05teqm2km0f66.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.travel_app',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDNbKHg9KrTJUajMjcTHTqz-nYJXRTufUg',
  //   appId: '1:551484186975:android:05a84133ac7f052e5016ea',
  //   messagingSenderId: '551484186975',
  //   projectId: 'travelapp-8e93c',
  //   storageBucket: 'fir-auth-demo-ec48c.appspot.com',
  //   iosClientId: '599030350718-rt5diuiggpna5fmco6k05teqm2km0f66.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.travel_app',
  // );
}
